# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "05f95f63f2b874fd2f6103a4ebb7d697"
name = "kourify-shopping-guaranteey\r"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_metaobject_definitions,write_metaobjects,write_products"

[app_proxy]
url = "/proxy"
subpath = "kourify"
prefix = "apps"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
